# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    download_directory: '../public/'
    admin_email: admin@admin.com
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $globalParam: 'global param to be used by all services defined in this file'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # autowire: true means that we can do without the code below
    # App\Services\MyService:
    #     arguments:
    #         $second_service: '@App\Services\MySecondService'


    App\Services\MyService:
        arguments:
            $service: '@App\Services\MySecondService'
    App\Services\MySecondService:
        # this service will be instantiated only if an instance will be 
        # explicitly created or if a method of this class will be directly called, 
        # which leads to an instantiation of this class
        lazy: true